DEBUG = True
SECRET_KEY = 'SECRET_KEY'
SECURITY_PASSWORD_SALT = 'SECURITY_PASSWORD_SALT'
SQLALCHEMY_DATABASE_URI = ''  # dialect+driver://username:password@host:port/database
SQLALCHEMY_TRACK_MODIFICATIONS = True
UPLOAD_FOLDER = ''
ALLOWED_EXTENSIONS = {'pdf', 'docx'}

# For mail
MAIL_SERVER = 'smtp.gmail.com'
MAIL_PORT = 465
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_USERNAME = ''
MAIL_PASSWORD = ''
MAIL_DEFAULT_SENDER = ''
